name: Run Cypress Tests

on:
    push:
        branches: [main]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.18.0"

            - name: Install dependencies
              run: npm install

            - name: Create .env file
              run: |
                  touch .env
                  echo "KINDE_SITE_URL=${{ secrets.KINDE_SITE_URL }}" >> .env
                  echo "KINDE_POST_LOGOUT_REDIRECT_URL=${{ secrets.KINDE_POST_LOGOUT_REDIRECT_URL }}" >> .env
                  echo "KINDE_POST_LOGIN_REDIRECT_URL=${{ secrets.KINDE_POST_LOGIN_REDIRECT_URL }}" >> .env
                  echo "KINDE_LOGIN_PWD=${{ secrets.KINDE_LOGIN_PWD }}" >> .env
                  echo "KINDE_LOGIN_EMAIL=${{ secrets.KINDE_LOGIN_EMAIL }}" >> .env
                  echo "KINDE_ISSUER_URL=${{ secrets.KINDE_ISSUER_URL }}" >> .env
                  echo "KINDE_CLIENT_SECRET=${{ secrets.KINDE_CLIENT_SECRET }}" >> .env
                  echo "KINDE_CLIENT_ID=${{ secrets.KINDE_CLIENT_ID }}" >> .env
                  echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
                  echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> .env
                  echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> .env
                  echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
                  cat .env

            - name: Run Cypress tests
              run: npm run test:e2e:run
